### ISSUE TITLE
[GTEx] Identify FHIR DocumentReferences for Gene Expression Summary files

### ISSUE THREAD

**Issue by RobertJCarroll** [NIH-NCPI/FHIR-CAT-June22#9]
Save JSON containing all DocumentReferences for GTEx Gene Expression Summary files into this bucket: https://console.cloud.google.com/storage/browser/fc-be286b9f-3acf-4168-af6e-592df509391d/DocumentReference
gs://fc-be286b9f-3acf-4168-af6e-592df509391d/DocumentReference

**Comment by torstees** [comment]
The following query will pull the RNA specific DocumentReferences from GTEx. There are no type codes currently associated with the data so the query is only suitable because this is the only type of data we have inside the FHIR server:

https://healthcare.googleapis.com/v1/projects/ncpi-fhir-cat-2022/locations/us-central1/datasets/GTEx_Open_Access/fhirStores/gtex_v8.2/fhir/category=RNA-Seq&location:missing=false

**Comment by ianfore** [comment]
**For Kids First Study - ResearchStudy/48656**
SD_8Y99QZJJ
Pediatric Brain Tumor Atlas: PNOC

Accessible file count by type
{'tbi': 5, 'maf': 5, 'vcf': 5}
Inaccessible file count by type
{'tbi': 12, 'vcf': 11, 'maf': 10, 'bam': 7, 'cram': 2, 'crai': 2, 'bai': 1, 'gvcf': 1})

**Comment by RobertJCarroll** [comment]
See #12
